---
hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Over mij
description: Gebruik de programmeertaal Python om afbeeldingen van tekst te maken
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introductie
  - 
    title: Wat je nodig hebt
  - 
    title: Hallo zeggen
  - 
    title: "Uitdaging: waar denk je aan?"
  - 
    title: ASCII-kunst
  - 
    title: "Uitdaging: over jezelf"
  - 
    title: Het jaar 2025
  - 
    title: "Uitdaging: je leeftijd in hondenjaren"
  - 
    title: "Uitdaging: rekenen met tekst"
