hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: About me
description: Use the Python programming language to create pictures out of text
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Saying hello
- title: "Challenge: what's on your mind?"
- title: ASCII art
- title: "Challenge: about yourself"
- title: The year 2025
- title: "Challenge: your age in dog years"
- title: "Challenge: calculating text"