---
hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, production-0, community-0
title: Обо мне
description: Используйте язык программирования Python для создания изображений из текста
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Введение
  - 
    title: Что вам понадобится
  - 
    title: Сказать привет
  - 
    title: "Задание: написать о чем вы думаете"
  - 
    title: Искусство ASCII
  - 
    title: "Задание: о себе"
  - 
    title: 2025-ый год
  - 
    title: "Задание: ваш возраст в системе отсчета собачьих годов"
  - 
    title: "Задание: арифметика текста"
