---
hero_image: చిత్రాలు / గురించి-me.png
theme: నారింజ
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, డిజైన్ -0, ప్రోగ్రామింగ్ -1, ఫిజిక్స్- comp-0, తయారీ-0, కమ్యూనిటీ 0
title: నా గురించి
description: వచనం యొక్క చిత్రాలను రూపొందించడానికి పైథాన్ ప్రోగ్రామింగ్ లాంగ్వేజ్ ఉపయోగించండి
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: పైథాన్
site_areas: ప్రాజెక్టులు
hardware: ''
software: పైథాన్
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: పరిచయం
  - 
    title: మీరు అవసరం ఏమిటి
  - 
    title: హలో చెప్పడం
  - 
    title: "ఛాలెంజ్: మీ మనసులో ఏముంది?"
  - 
    title: ASCII కళ
  - 
    title: "ఛాలెంజ్: మీ గురించి"
  - 
    title: సంవత్సరం 2025
  - 
    title: "ఛాలెంజ్: కుక్క సంవత్సరాలలో మీ వయస్సు"
  - 
    title: "ఛాలెంజ్: టెక్స్ట్ లెక్కిస్తోంది"
