---
hero_image: beelde / oor-me.png
theme: oranje
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, ontwerp-0, programmering-1, fis-komp-0, vervaardiging-0, gemeenskap-0
title: Oor my
description: Gebruik die Python programmeertaal om prente uit teks te skep
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: projekte
hardware: ''
software: python
version: 3
last_tested: 2017/01/01
steps:
  - 
    title: inleiding
  - 
    title: Wat jy benodig
  - 
    title: Sê hallo
  - 
    title: "Uitdaging: wat dink jy?"
  - 
    title: ASCII art
  - 
    title: "Uitdaging: oor jouself"
  - 
    title: Die jaar 2025
  - 
    title: "Uitdaging: jou ouderdom in hondjare"
  - 
    title: "Uitdaging: berekening van teks"
