---
hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Thông tin về tôi
description: Sử dụng ngôn ngữ lập trình Python để tạo hình ảnh từ văn bản
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Giới thiệu
  - 
    title: Những gì bạn sẽ cần
  - 
    title: Nói xin chào
  - 
    title: 'Thử thách: Bạn đang nghĩ gì?'
  - 
    title: ASCII art
    completion:
      - engaged
  - 
    title: 'Thử thách: về bản thân'
  - 
    title: Năm 2025
    completion:
      - internal
  - 
    title: 'Thử thách: tuổi của bạn tính theo năm chó'
  - 
    title: 'Thử thách: tính toán văn bản'
