---
hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Su di me
description: Usa il linguaggio di programmazione Python per creare immagini senza testo
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: codeclub, python
steps:
  - 
    title: Introduzione
  - 
    title: Di cosa avrai bisogno
  - 
    title: Salutare
  - 
    title: 'Sfida: Cosa stai pensando?'
  - 
    title: Arte ASCII
  - 
    title: 'Sfida: Chi sei'
  - 
    title: L’anno 2025
  - 
    title: 'Sfida: La tua età in anni canini'
  - 
    title: 'Sfida: Calcolare testo'
