---
hero_image: images/about-me.png
theme: oranssi
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, ohjelmointi-1, phys-comp-0, valmistus-0, yhteisö-0
title: Minusta
description: Python-ohjelmointikielellä voit luoda kuvia tekstistä
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: projektit
hardware: ''
software: python
version: 3
last_tested: 01.1.2017
steps:
  - 
    title: Johdanto
  - 
    title: Mitä tarvitset
  - 
    title: Tervehtiä
  - 
    title: "Haaste: mitä on mielessäsi?"
  - 
    title: ASCII-taide
  - 
    title: "Haaste: kerro itsestäsi"
  - 
    title: Vuosi 2025
  - 
    title: "Haaste: ikäsi koiran vuosissa"
  - 
    title: "Haaste: tekstin laskeminen"
