---
hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Sobre mi
description: Utiliza el lenguaje de programación Python para crear imágenes a partir de caracteres de texto
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Lo que necesitarás
  - 
    title: Decir hola
  - 
    title: 'Reto: ¿en qué estás pensando?'
  - 
    title: Arte ASCII
    completion:
      - engaged
  - 
    title: 'Reto: sobre ti'
  - 
    title: El año 2025
    completion:
      - internal
  - 
    title: 'Reto: tu edad en años de perro'
  - 
    title: 'Reto: calcular texto'
