---
hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Amdana i
description: Defnyddio iaith rhaglenni Python i greu lluniau yn defnyddio testun
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Cyflwyniad
- title: Beth fydd angen
  completion: engaged
- title: Dweud helo
- title: 'Her: beth sydd ar dy feddwl di?'
- title: Celf ASCII
- title: 'Her: amdano ti'
- title: Y flwyddyn 2025
- title: 'Her: dy oedran mewn blynyddoedd ci'
  completion: internal
- title: 'Her: cyfrifo testun'
