---
hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Sobre mi
description: Utiliza el lenguaje de programación Python para crear cuadros de texto
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: codeclub, python
steps:
  - 
    title: Introducción
  - 
    title: Lo que necesitarás
  - 
    title: Decir hola
  - 
    title: 'Reto: ¿en qué estás pensando?'
  - 
    title: Arte ASCII
  - 
    title: 'Reto: sobre ti'
  - 
    title: El año 2025
  - 
    title: 'Reto: tu edad en años de perro'
  - 
    title: 'Reto: calcular texto'
