---
hero_image: images/about-me.png
theme: naranja
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creador, diseño-0, programación-1, informática-física-0, fabricación-0, comunidad-0
title: Sobre mi
description: Utiliza el lenguaje de programación Python para crear cuadros de texto
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: codeclub, python
steps:
  - 
    title: Introducción
  - 
    title: Lo que necesitarás
  - 
    title: Decir hola
  - 
    title: 'Desafío: ¿qué tienes en la cabeza?'
  - 
    title: Arte ASCII
  - 
    title: 'Desafío: sobre ti'
  - 
    title: El año 2025
  - 
    title: 'Desafío: tu edad en años de perro'
  - 
    title: 'Desafío: calcular el texto'
