---
hero_image: images/about-me.png
theme: naranja
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creador, diseño-0, programación-1, informática-física-0, fabricación-0, comunidad-0
title: Sobre mí
description: Utiliza el lenguaje de programación Python para crear cuadros de texto
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: codeclub, python
steps:
  - 
    title: Introducción
  - 
    title: Lo que necesitarás
  - 
    title: Decir hola
  - 
    title: 'Challenge: what''s on your mind?'
  - 
    title: ASCII art
  - 
    title: 'Challenge: about yourself'
  - 
    title: The year 2025
  - 
    title: 'Challenge: your age in dog years'
  - 
    title: 'Challenge: calculating text'
