---
hero_image: Bilder/über-mich.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Über Mich
description: Schreibe über dich und erstelle Bilder von dir
original_url: https://projects.raspberrypi.org/en/projects/about-me
interests: ''
technologies: Python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einführung
  - 
    title: Hallo sagen
  - 
    title: 'Aufgabe: An was denkst du?'
  - 
    title: "ASCII Bild"
  - 
    title: 'Aufgabe: Über Dich'
  - 
    title: "Das Jahr 2025"
  - 
    title: 'Aufgabe: Alter in Hundejahren'
  - 
    title: "Aufgabe: Text berechnen"
  - 
    title: "Challenge: Einen Text berechnen"
