---
hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Über Mich
description: Verwende die Programmiersprache Python, um Bilder aus Text zu erstellen
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - title: Einleitung
  - title: Was du brauchen wirst
  - title: Hallo sagen
  - title: "Herausforderung: Was beschäftigt dich?"
  - title: ASCII Kunst
  - title: "Herausforderung: Über dich"
  - title: Das Jahr 2025
  - title: "Herausforderung: Dein Alter in Hundejahren"
  - title: "Herausforderung: Text berechnen"
