---
hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Despre mine
description: Folosește limbajul de programare Python pentru a crea imagini dintr-un text
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducere
  - 
    title: De ce vei avea nevoie
  - 
    title: Cum să saluți
  - 
    title: 'Provocare: la ce te gândești?'
  - 
    title: Artă ASCII
    completion:
      - engaged
  - 
    title: 'Provocare: despre tine'
  - 
    title: Anul 2025
    completion:
      - internal
  - 
    title: 'Provocare: vârsta ta în ani canini'
  - 
    title: 'Provocare: calculează un text'
