---
hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: O mně
description: Použij programovací jazyk Python a vytvářej obrázky z textu
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Úvod
  - 
    title: Co budeš potřebovat
  - 
    title: Řekni ahoj
  - 
    title: "Výzva: na co myslíš?"
  - 
    title: ASCII grafika
  - 
    title: "Výzva: o sobě"
  - 
    title: V roce 2025
  - 
    title: "Výzva: psí věk"
  - 
    title: "Výzva: počítání s textem"
