---
hero_image: images/about-me.png
theme: כָּתוֹם
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: פרטים אודותי
description: השתמש בפיתון כדי ליצור תמונות מתוך טקסט
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: פיתון
site_areas: פרויקטים
hardware: ''
software: פיתון
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: הקדמה
  - 
    title: מה נדרש
  - 
    title: אמור שלום
  - 
    title: "האתגר: על מה אתה חושב?"
  - 
    title: אמנות ASCII
  - 
    title: "האתגר: על עצמך"
  - 
    title: שנת 2025
  - 
    title: "האתגר: חשב את הגיל שלך בשנים של כלב"
  - 
    title: "אתגר: חישוב טקסט"
