---
hero_image: images / about-me.png
theme: narancs
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programozás-1, phys-comp-0, gyártás-0, community-0
title: Rólam
description: Használja a Python programnyelvét szövegek létrehozásához
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: piton
site_areas: projektek
hardware: ''
software: piton
version: 3
last_tested: 2017/01/01
steps:
  - 
    title: Bevezetés
  - 
    title: Amire szükséged lesz
  - 
    title: Köszönni
  - 
    title: "Kihívás: mi a véleményed?"
  - 
    title: ASCII művészet
  - 
    title: "Kihívás: magadról"
  - 
    title: A 2025-ös év
  - 
    title: "Kihívás: az életkor a kutyaévekben"
  - 
    title: "Kihívás: a szöveg kiszámítása"
