---
hero_image: images/about-me.png
theme: narancs
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Rólam
description: Használja a Python programnyelvet szövegből képek létrehozásához
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Bevezetés
  - 
    title: Amire szükséged lesz
  - 
    title: Üdvözlés
  - 
    title: "Kihívás: mit gondolsz?"
  - 
    title: ASCII művészet
  - 
    title: "Kihívás: rólad"
  - 
    title: A 2025-ös év
  - 
    title: "Kihívás: életkorod kutyaévekben"
  - 
    title: "Kihívás: a szöveg kiszámítása"
