---
hero_image: 圖片/關於我. png
theme: 橘色
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 創作者，設計-0，寫程式-1，物理-comp-0，製造-0，社團-0
title: 關於我
description: 使用 Python 程式設計語言在文字中創建圖片
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: codeclub，python
steps:
  - 
    title: 介紹
  - 
    title: 你將需要什麼
  - 
    title: 打招呼
  - 
    title: 挑戰：你在想什麼？
  - 
    title: ASCII藝術
  - 
    title: 挑戰：關於你自己
  - 
    title: 2025年
  - 
    title: '挑戰: 你的年齡在狗年'
  - 
    title: 挑戰：計算文字
