---
hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Sobre mí
description: Utiliza el lenguaje de programación Python para crear imágenes a partir
  de texto
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introducción
- title: Lo que necesitarás
  completion: engaged
- title: Aprendiendo a saludar
- title: 'Desafío: ¿en qué estás pensando?'
- title: Arte ASCII
- title: 'Desafío: sobre ti'
- title: El año 2025
- title: 'Desafío: tu edad en años de perro'
  completion: internal
- title: 'Desafío: calculando texto'
