---
hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: O mnie
description: Używamy języka programowania Python do tworzenia obrazków z tekstu
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Czego będziesz potrzebować
  - 
    title: Mówimy "cześć"
  - 
    title: "Wyzwanie: o czym myślisz?"
  - 
    title: ASCII art
  - 
    title: "Wyzwanie: o sobie"
  - 
    title: Rok 2025
  - 
    title: "Wyzwanie: twój wiek w psich latach"
  - 
    title: "Wyzwanie: obliczanie tekstu"
