---
hero_image: images/about-me.png
theme: oranžová
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, návrh-0, programovanieg-1, phys-comp-0, výroba-0, spoločnosť-0
title: O mne
description: Použi programovací jazyk Python na vytvorenie obrázkov z textu
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: projekty
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Úvod
  - 
    title: Čo budeš potrebovať
  - 
    title: Povedz ahoj
  - 
    title: "Výzva: na čo myslíš?"
  - 
    title: ASCII art
  - 
    title: "Výzva: o tebe"
  - 
    title: Rok 2025
  - 
    title: "Výzva: tvoj vek v psích rokoch"
  - 
    title: "Výzva: počítanie s textom"
