---
hero_image: images/about-me.png
theme: কমলা
duration: 0
listed: true
ingredient: false
copyedit: true
curriculum: 1, ডিজাইন -1, প্রোগ্রামিং -1, ফিজিক্যাল-কম্পিউটিং-0, উৎপাদন-0, কমিউনিটি -0
title: আমার পরিচয়
description: টেক্সট থেকে ছবি তৈরি করতে প্রোগ্রামিং ল্যাংগুয়েজ Python (পাইথন) ব্যবহার করুন
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: পাইথন (python)
site_areas: প্রকল্পসমূহ
hardware: ''
software: পাইথন (python)
version: 3
last_tested: ২০১৭-০১-০১
steps:
  - 
    title: ভূমিকা
  - 
    title: যা যা প্রয়োজন
  - 
    title: হ্যালো বলা
  - 
    title: "দেখা যাক: আপনি কি চিন্তা করছেন?"
  - 
    title: ASCII শিল্প
  - 
    title: "প্রতিযোগিতা: আপনার সম্পর্কে"
  - 
    title: ২০২৫ সাল
  - 
    title: "প্রতিযোগিতা: কুকুরের আয়ু অনুযায়ী আপনার বয়স"
  - 
    title: "প্রতিযোগিতা: অক্ষর গণনা"
