---
hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: A propos de moi
description: Utilise le langage de programmation Python pour dessiner avec du texte
original_url: https://projects.raspberrypi.org/en/projects/about-me
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - title: Introduction
  - title: Ce qu'il te faut
  - title: Dire bonjour
  - title: "Défi: à quoi penses-tu?"
  - title: Art ASCII
  - title: "Défi: à propos de toi"
  - title: L'année 2025
  - title: "Défi: ton âge en années de chien"
  - title: "Défi: calculer du texte"
