---
hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Mi presento
description: Usa il linguaggio di programmazione Python per creare delle immagini a partire da un testo
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: codeclub, python
steps:
  - 
    title: Introduzione
  - 
    title: Requisiti
  - 
    title: Diciamo ciao
  - 
    title: 'Sfida: A cosa stai pensando?'
  - 
    title: Disegni ASCII
  - 
    title: 'Sfida: Mi presento'
  - 
    title: Nel 2025
  - 
    title: 'Sfida: La tua età in anni canini'
  - 
    title: 'Sfida: Calcolare un testo'
