---
hero_image: images/about-me.png
theme: turuncu
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, tasarım-0, programlama-1, fiziksel-hesaplama-0, üretim-0, topluluk-0
title: Hakkımda
description: Python programlama dilini kullanarak yazı karakterlerinden resim oluşturun
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: projeler
hardware: ''
software: python
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: Giriş
  - 
    title: Nelere ihtiyacınız olacak
  - 
    title: Merhaba demek
  - 
    title: "Meydan okuma: Aklında ne var?"
  - 
    title: ASCII sanatı
  - 
    title: "Meydan okuma: kendin hakkında"
  - 
    title: 2025 yılı
  - 
    title: "Meydan okuma: Köpek takvimine göre yaşınız"
  - 
    title: "Meydan okuma: metin hesaplama"
