---
hero_image: images/about-me.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Hakkımda
description: Python programlama dilini kullanarak yazı karakterlerinden resim oluşturun
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - title: Giriş
  - title: Nelere ihtiyacınız olacak
  - title: Merhaba demek
  - title: "Meydan okuma: Aklında ne var?"
  - title: ASCII sanatı
  - title: "Meydan okuma: kendin hakkında"
  - title: 2025 yılı
  - title: "Meydan okuma: Köpek takvimine göre yaşınız"
  - title: "Meydan okuma: metin hesaplama"
